-- ============================================================
-- 6. LOGIN LOGS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS public.login_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  email text NOT NULL,
  phone text,
  role text,
  user_details jsonb,
  ip_address text,
  user_agent text,
  access_token text,
  logged_in_at timestamptz NOT NULL DEFAULT now(),
  logged_out_at timestamptz,
  is_active boolean NOT NULL DEFAULT true
);

-- Enable RLS
ALTER TABLE public.login_logs ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Login logs are viewable by owner" ON public.login_logs;
CREATE POLICY "Login logs are viewable by owner"
  ON public.login_logs
  FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Login logs can be inserted by owner" ON public.login_logs;
CREATE POLICY "Login logs can be inserted by owner"
  ON public.login_logs
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Login logs can be updated by owner" ON public.login_logs;
CREATE POLICY "Login logs can be updated by owner"
  ON public.login_logs
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
